Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Models/EmpleadoModel.cs
using System.ComponentModel.DataAnnotations;
using System.Data.SqlTypes;

namespace CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA.Models
{
    public class EmpleadoModel
    {
        public int id { get; set; }

        [Required(ErrorMessage = "El campo nombre es requerido.")]
        public string? Nombre { get; set; }
        [Required(ErrorMessage = "El campo salario es requerido.")]
        public int? Salario { get; set; }

    }
}

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Models/ErrorViewModel.cs
namespace CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Controllers/HomeController.cs
using CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Controllers/MantenedorController.cs
using Microsoft.AspNetCore.Mvc;
using CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA.Datos;
using CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA.Models;


namespace CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA.Controllers
{
    public class MantenedorController : Controller
    {
        EmpleadoDatos _EmpleadoDatos = new EmpleadoDatos();
        public IActionResult Listar()
        {
            //La vista mostrara una lista de empleados
            var objectLista = _EmpleadoDatos.Listar();
            return View(objectLista);
        }

        public IActionResult Guardar()
        {
            //metodo que solo devuelve la vista
            return View();
        }

        [HttpPost]
        public IActionResult Guardar(EmpleadoModel objectEmpleado)
        {
            //metodo que recibe el objeto para guardarlo en la base de datos
            if (!ModelState.IsValid)
                return View();

            var respuesta = _EmpleadoDatos.Guardar(objectEmpleado);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Modificar(int ID_Empleado)
        {
            //metodo que solo devuelve la vista
            var objectEmpleado = _EmpleadoDatos.Obtener(ID_Empleado);
            return View(objectEmpleado);
        }

        [HttpPost]
        public IActionResult Modificar(EmpleadoModel objectEmpleado)
        {
            //metodo que recibe el objeto para editarlo en la base de datos
            if (!ModelState.IsValid)
                return View();

            var respuesta = _EmpleadoDatos.Modificar(objectEmpleado);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult Eliminar(int ID_Empleado)
        {
            //metodo que solo devuelve la vista
            var objectEmpleado = _EmpleadoDatos.Obtener(ID_Empleado);
            return View(objectEmpleado);
        }

        [HttpPost]
        public IActionResult Eliminar(EmpleadoModel objectEmpleado)
        {
            //metodo que recibe el objeto para eliminarlo en la base de datos
            var respuesta = _EmpleadoDatos.Eliminar(objectEmpleado.id);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

    }
}

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Views/Mantenedor/Eliminar.cshtml
@model EmpleadoModel
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Eliminar Empleado
    </div>
    <div class="card-body">
        <form asp-action="Eliminar" asp-controller="Mantenedor" method="post">
            <input asp-for="id" type="hidden" class="form-control">

            <div class="alert alert-danger" role="alert">
                ¿Desea eliminar al empleado: @Html.DisplayTextFor(m => m.Nombre)?
            </div>

            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Views/Mantenedor/Guardar.cshtml
@model EmpleadoModel
@{
    ViewData["Title"] = "Guardar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Insertar Empleado
    </div>
    <div class="card-body">
        <form asp-action="Guardar" asp-controller="Mantenedor" method="post">
            <div class="mb-3">
                <label  class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Salario</label>
                <input asp-for="Salario" type="number" class="form-control">
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Views/Mantenedor/Listar.cshtml
@model List<EmpleadoModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Lista Empleado
    </div>
    <div class="card-body">
        <a asp-action="Guardar" asp-controller="Mantenedor" class="btn btn-success">Crear nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Salario</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.id</td>
                        <td>@item.Nombre</td>
                        <td>@item.Salario</td>
                        <td>
                            <a asp-action="Modificar" asp-controller="Mantenedor" class="btn btn-primary btn-sm" 
                                asp-route-ID_Empleado="@item.id">Modificar</a>
                            <a asp-action="Eliminar" asp-controller="Mantenedor" class="btn btn-danger btn-sm"
                                asp-route-ID_Empleado="@item.id">Eliminar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Views/Mantenedor/Modificar.cshtml
@model EmpleadoModel
@{
    ViewData["Title"] = "Modificar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        Modificar Empleado
    </div>
    <div class="card-body">
        <form asp-action="Modificar" asp-controller="Mantenedor" method="post">
            <input asp-for="id" type="hidden" class="form-control">
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input asp-for="Nombre" type="text" class="form-control">
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Salario</label>
                <input asp-for="Salario" type="number" class="form-control">
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Modificar</button>
            <a asp-action="Listar" asp-controller="Mantenedor" class="btn btn-warning">Volver a la lista</a>
        </form>
    </div>
</div>

Tarea1/CRUD-TAREA1-FELIXMENDEZ_PAMELAMORATAYA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CRUD_TAREA1_FELIXMENDEZ_PAMELAMORATAYA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>